Repository lion-packages/framework, pull requests merged in 2025-01, with the labels that each got.

#74 Support for PHP 8.4 and lion/bundle v18.0.0
  .env.actions
  .github/workflows/php.yml
  .gitignore
  Dockerfile
  app/Console/Commands/EncryptValueAESCommand.php
  app/Http/Controllers/LionDatabase/MySQL/AuthenticatorController.php
  app/Http/Controllers/LionDatabase/MySQL/LoginController.php
  app/Http/Controllers/LionDatabase/MySQL/RegistrationController.php
  app/Http/Controllers/LionDatabase/MySQL/UsersController.php
  app/Http/Middleware/JWTMiddleware.php
  app/Http/Services/JWTService.php
  app/Http/Services/LionDatabase/MySQL/AccountService.php
  app/Http/Services/LionDatabase/MySQL/LoginService.php
  composer.json
  composer.lock
  tests/Api/LionDatabase/MySQL/LoginControllerTest.php
  tests/App/Http/Controllers/LionDatabase/MySQL/LoginControllerTest.php
  tests/App/Http/Services/JWTServiceTest.php
Labels: enhancement, dependencies, continuous integration

#75 Viewing test results in Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#76 Documentation files are relocated
  .github/CHANGELOG.md
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.MD
  .github/LICENSE
  .github/README.md
Labels: documentation

#77 Documentation files are relocated (LICENSE)
  LICENSE
Labels: documentation

#78 Update with lion/bundle v18.1.0
  .env.actions
  .github/workflows/php.yml
  Dockerfile
  composer.json
  routes/middleware.php
  routes/web.php
Labels: enhancement, dependencies, continuous integration

#79 .htaccess configuration is updated
  .github/workflows/php.yml
  public/.htaccess
Labels: enhancement

#80 Updated Github Actions settings
  .github/workflows/php.yml
Labels: continuous integration

#81 Updated Github Actions settings
  .github/workflows/php.yml
Labels: continuous integration

#82 Auto loading of classes configured
  .gitignore
  config/bootstrap.php
  config/bootstrap.test.php
  phpunit.xml
  public/index.php
  tests/build/coverage/.gitignore
  tests/build/logs/.gitignore
Labels: enhancement

#83 Update with lion/bundle v18.2.0
  composer.json
Labels: dependencies

#85 Update LICENSE
  LICENSE
Labels: documentation
