Repository lion-packages/framework, pull requests merged in 2025-02, with the labels that each got.

#87 Added a resources directory for vite/astro projects
  resources/.gitignore
  vite/lion/.eslintrc.cjs
  vite/lion/.gitignore
  vite/lion/README.md
  vite/lion/index.html
  vite/lion/package-lock.json
  vite/lion/package.json
  vite/lion/public/vite.svg
  vite/lion/src/Api.jsx
  vite/lion/src/App.jsx
  vite/lion/src/assets/css/index.css
  vite/lion/src/assets/img/google-authenticator.png
  vite/lion/src/assets/img/icon-white.png
  vite/lion/src/components/AlertResponse.jsx
  vite/lion/src/components/Header.jsx
  vite/lion/src/components/LoadingScreen.jsx
  vite/lion/src/context/AuthContext.jsx
  vite/lion/src/context/ResponseContext.jsx
  vite/lion/src/context/account/ProfileContext.jsx
  vite/lion/src/context/site-administration/UsersContext.jsx
  vite/lion/src/hooks/useAES.jsx
  vite/lion/src/hooks/useApiResponse.jsx
  vite/lion/src/main.jsx
  vite/lion/src/middleware/AuthenticatedMiddleware.jsx
  vite/lion/src/middleware/NotAuthenticatedMiddleware.jsx
  vite/lion/src/middleware/RolesMiddleware.jsx
  vite/lion/src/pages/account/profile/ProfileIndex.jsx
  vite/lion/src/pages/account/profile/components/ChangePasswordModal.jsx
  vite/lion/src/pages/account/profile/components/ConfirmPasswordModal.jsx
  vite/lion/src/pages/account/profile/components/Disable2FAModal.jsx
  vite/lion/src/pages/account/profile/components/Enable2FAModal.jsx
  vite/lion/src/pages/account/profile/components/ProfileGeneral.jsx
  vite/lion/src/pages/account/profile/components/ProfileInformation.jsx
  vite/lion/src/pages/account/profile/components/ProfileSecurity.jsx
  vite/lion/src/pages/auth/login/LoginIndex.jsx
  vite/lion/src/pages/auth/login/components/Authenticator2FA.jsx
  vite/lion/src/pages/auth/login/components/VerifiedUser.jsx
  vite/lion/src/pages/auth/recovery-password/RecoveryPasswordIndex.jsx
  vite/lion/src/pages/auth/recovery-password/components/RecoveryPassword.jsx
  vite/lion/src/pages/auth/register/RegisterIndex.jsx
  vite/lion/src/pages/dashboard/DashboardIndex.jsx
  vite/lion/src/pages/errors/NotFound.jsx
  vite/lion/src/pages/errors/Unauthorized.jsx
  vite/lion/src/pages/site-administration/users/UsersIndex.jsx
  vite/lion/src/pages/site-administration/users/components/Buttons.jsx
  vite/lion/src/pages/site-administration/users/components/UsersCreate.jsx
  vite/lion/src/pages/site-administration/users/components/UsersRead.jsx
  vite/lion/src/pages/site-administration/users/components/UsersUpdate.jsx
  vite/lion/src/setupTests.js
  vite/lion/tests/context/ResponseContext.test.jsx
  vite/lion/tests/hooks/useApiResponse.test.jsx
  vite/lion/tests/pages/components/AlertResponse.test.jsx
  vite/lion/vite.config.js
Labels: enhancement

#88 Update CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#89 Update with lion/bundle v18.3.2
  .github/workflows/php.yml
  composer.json
  config/bootstrap.php
  config/bootstrap.test.php
  phpstan.neon
  tests/.gitignore
  tests/AppTest.php
Labels: dependencies, tests, continuous integration

#90 Docker configuration is updated
  docker-compose.yml
Labels: continuous integration

#91 Update with lion/bundle v18.4.0
  composer.json
Labels: dependencies

#92 .env properties are modified
  .env.actions
  .env.example
  config/database.php
  lion
  npm
Labels: enhancement

#93 Update with lion/bundle v18.6.0
  composer.json
  routes/middleware.php
Labels: dependencies

#94 Update with lion/bundle v18.7.0
  composer.json
  config/cors.php
  config/database.php
  config/email.php
  routes/web.php
Labels: dependencies
