Repository lion-packages/framework, pull requests merged in 2025-04, with the labels that each got.

#99 Integrate Dependency-Review
  .github/workflows/php.yml
Labels: continuous integration

#101 Headers are added in the cors configuration
  config/cors.php
Labels: enhancement

#100 Ping is added to validate local server
  .github/workflows/php.yml
Labels: continuous integration

#102 Integrate PHPLint
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration

#103 Test is added
  .github/workflows/php.yml
  tests/AppTest.php
Labels: tests

#104 Test is added
  tests/AppTest.php
Labels: tests

#105 Add Dependabot configuration
  .github/dependabot.yml
Labels: continuous integration

#106 Modify class imports
  app/Console/Cron/.gitignore
  config/bootstrap.php
  routes/middleware.php
  tests/AppTest.php
Labels: enhancement

#107 Update dependabot.yml
  .github/dependabot.yml
Labels: continuous integration

#108 Apply fixes from StyleCI
  tests/AppTest.php
Labels: standardization

#109 Added StyleCI configuration
  .styleci.yml
Labels: continuous integration

#111 Define the execution time for Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#112 Define the runtime for the Dependabot
  .github/dependabot.yml
Labels: continuous integration

#113 Added support for catching exceptions
  config/bootstrap.php
  config/bootstrap.test.php
  config/exception.handler.php
Labels: enhancement
