Repository lion-packages/framework, pull requests merged in 2025-03, with the labels that each got.

#95 Update with lion/bundle v18.8.0
  composer.json
Labels: dependencies

#96 Update with lion/bundle v18.9.0
  composer.json
  phpunit.xml
Labels: dependencies

#98 Update README.md
  .github/README.md
Labels: documentation

#97 Add cache in workflow
  .github/workflows/php.yml
Labels: continuous integration
